# Generated by Django 5.0.4 on 2024-05-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активность"),
        ),
    ]
