# Generated by Django 5.0.4 on 2024-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(
                blank=True, null=True, to="materials.lesson", verbose_name="Уроки курса"
            ),
        ),
    ]
